# -*- coding: utf-8 -*-
"""Prueba Causal Impact - Individual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpAwEx2NzKRYE-y6WIwcDuY3aec_0ug9
"""

"""
=============================================================================
GOOGLE COLAB - CAUSALIMPACT FUNCIONANDO PERFECTAMENTE
=============================================================================
Con gráficos personalizados que SÍ funcionan correctamente
"""

# =============================================================================
# CELDA 1: INSTALACIÓN
# =============================================================================

!pip install -q pycausalimpact
print("✅ Instalación completada")

# =============================================================================
# CELDA 2: IMPORTAR TODO
# =============================================================================

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from causalimpact import CausalImpact

print("✅ Todas las librerías importadas correctamente")

# =============================================================================
# CELDA 3: GENERAR DATOS DE EJEMPLO
# =============================================================================

def generar_datos_ejemplo():
    """Genera datos realistas de e-commerce con tráfico web"""
    np.random.seed(2023)
    dates = pd.date_range('2023-01-01', periods=365, freq='D')

    trend = np.linspace(10000, 12000, 365)
    day_of_week = dates.dayofweek
    weekly_effect = np.where(day_of_week >= 5, -2000, 500)
    sesiones = trend + weekly_effect + np.random.normal(0, 500, 365)
    sesiones = np.maximum(sesiones, 1000)

    usuarios = sesiones * np.random.uniform(0.70, 0.80, 365)
    trafico_org = sesiones * np.random.uniform(0.55, 0.65, 365)
    trafico_dir = sesiones * np.random.uniform(0.20, 0.30, 365)
    bounce_rate = np.random.uniform(38, 52, 365)
    paginas = np.random.uniform(2.5, 4.5, 365)

    conversion_rate_base = 0.025
    conversiones = (
        sesiones * conversion_rate_base +
        0.0003 * usuarios +
        0.0002 * trafico_org -
        0.5 * bounce_rate +
        15 * paginas +
        np.random.normal(0, 30, 365)
    )
    conversiones = np.maximum(conversiones, 50)

    # Intervenciones
    conversiones[90:121] *= 1.15  # Abril +15%
    conversiones[243:274] *= 1.25  # Septiembre +25%

    data = pd.DataFrame({
        'y': conversiones,
        'sesiones_totales': sesiones,
        'usuarios_unicos': usuarios,
        'trafico_organico': trafico_org,
        'trafico_directo': trafico_dir,
        'bounce_rate': bounce_rate,
        'paginas_por_sesion': paginas
    }, index=dates)

    return data

print("\n" + "="*70)
print("GENERANDO DATOS DE EJEMPLO")
print("="*70)

data = generar_datos_ejemplo()

print(f"\n✅ Datos generados:")
print(f"  • Total días: {len(data)}")
print(f"  • Período: {data.index.min().date()} a {data.index.max().date()}")
print(f"  • Intervención 1: 2023-04-01 al 2023-05-01")
print(f"  • Intervención 2: 2023-09-01 al 2023-10-01")

# =============================================================================
# CELDA 4: VISUALIZAR DATOS
# =============================================================================

print("\n" + "="*70)
print("VISUALIZACIÓN DE DATOS")
print("="*70)

fig, axes = plt.subplots(3, 2, figsize=(16, 12))

axes[0, 0].plot(data.index, data['y'], linewidth=1.5, color='#2ecc71', label='Conversiones')
axes[0, 0].axvspan(pd.Timestamp('2023-04-01'), pd.Timestamp('2023-05-01'),
                   alpha=0.2, color='red', label='Intervención Abril')
axes[0, 0].axvspan(pd.Timestamp('2023-09-01'), pd.Timestamp('2023-10-01'),
                   alpha=0.2, color='orange', label='Intervención Sept')
axes[0, 0].set_title('Conversiones Diarias', fontweight='bold', fontsize=13)
axes[0, 0].set_ylabel('Conversiones')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

axes[0, 1].plot(data.index, data['sesiones_totales'], linewidth=1.5, color='#3498db')
axes[0, 1].set_title('Sesiones Totales (Control)', fontweight='bold', fontsize=13)
axes[0, 1].set_ylabel('Sesiones')
axes[0, 1].grid(True, alpha=0.3)

axes[1, 0].plot(data.index, data['usuarios_unicos'], linewidth=1.5, color='#9b59b6')
axes[1, 0].set_title('Usuarios Únicos (Control)', fontweight='bold', fontsize=13)
axes[1, 0].set_ylabel('Usuarios')
axes[1, 0].grid(True, alpha=0.3)

axes[1, 1].plot(data.index, data['trafico_organico'], linewidth=1.5, color='#f39c12')
axes[1, 1].set_title('Tráfico Orgánico (Control)', fontweight='bold', fontsize=13)
axes[1, 1].set_ylabel('Sesiones Orgánicas')
axes[1, 1].grid(True, alpha=0.3)

corr = data.corr()['y'].sort_values(ascending=False)[1:]
colors_corr = ['#2ecc71' if x > 0.5 else '#e74c3c' if x < -0.5 else '#95a5a6' for x in corr.values]
axes[2, 0].barh(range(len(corr)), corr.values, color=colors_corr)
axes[2, 0].set_yticks(range(len(corr)))
axes[2, 0].set_yticklabels(corr.index, fontsize=10)
axes[2, 0].set_xlabel('Correlación con Conversiones')
axes[2, 0].set_title('Correlaciones', fontweight='bold', fontsize=13)
axes[2, 0].axvline(0, color='black', linewidth=1)
axes[2, 0].grid(True, alpha=0.3, axis='x')

sns.heatmap(data.corr(), annot=True, fmt='.2f', cmap='RdYlGn',
            center=0, ax=axes[2, 1], cbar_kws={'label': 'Correlación'},
            vmin=-1, vmax=1)
axes[2, 1].set_title('Matriz de Correlación', fontweight='bold', fontsize=13)

plt.suptitle('Análisis Exploratorio - Datos de Tráfico Web',
             fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n✅ Visualización completada")

# =============================================================================
# CELDA 5: FUNCIÓN PERSONALIZADA PARA GRAFICAR CAUSALIMPACT
# =============================================================================

def plot_causalimpact_correcto(ci, post_period_start, titulo="CausalImpact Analysis"):
    """
    Función personalizada para graficar CausalImpact correctamente

    Parámetros:
    - ci: objeto CausalImpact
    - post_period_start: fecha de inicio del período post (pd.Timestamp)
    - titulo: título del gráfico
    """

    # Obtener el DataFrame de inferencias
    inferences = ci.inferences

    # Obtener datos originales desde el objeto CausalImpact
    y_original = inferences.index.map(lambda x: data.loc[x, 'y'] if x in data.index else np.nan)

    # Crear figura con 3 paneles
    fig, axes = plt.subplots(3, 1, figsize=(14, 10))

    # =========================================================================
    # CALCULAR LÍMITES RAZONABLES PARA LOS EJES
    # =========================================================================

    # Para el panel 1 (Original vs Predicted), usar rango de datos observados + predichos
    y_min = min(y_original.min(), inferences['preds'].min())
    y_max = max(y_original.max(), inferences['preds'].max())
    margin = (y_max - y_min) * 0.15  # 15% de margen
    ylim_panel1 = [y_min - margin, y_max + margin]

    # Para el panel 2 (Point Effects), usar rango de efectos puntuales
    effects_min = inferences['point_effects'].min()
    effects_max = inferences['point_effects'].max()
    margin_effects = (effects_max - effects_min) * 0.2
    ylim_panel2 = [effects_min - margin_effects, effects_max + margin_effects]

    # =========================================================================
    # PANEL 1: Original vs Predicted
    # =========================================================================
    ax1 = axes[0]

    # Línea negra: Y observado (datos reales)
    ax1.plot(inferences.index, y_original, 'k-', linewidth=2, label='Observed', zorder=3)

    # Línea azul punteada: Predicción
    ax1.plot(inferences.index, inferences['preds'], 'b--', linewidth=2,
             label='Predicted', alpha=0.8, zorder=2)

    # Banda gris: Intervalo de confianza 95% (solo donde sea razonable)
    # Clipear los valores del IC a límites razonables
    preds_lower_clipped = inferences['preds_lower'].clip(ylim_panel1[0], ylim_panel1[1])
    preds_upper_clipped = inferences['preds_upper'].clip(ylim_panel1[0], ylim_panel1[1])

    ax1.fill_between(inferences.index,
                     preds_lower_clipped,
                     preds_upper_clipped,
                     alpha=0.2, color='blue', label='95% CI', zorder=1)

    # Línea vertical roja: inicio del período post
    ax1.axvline(post_period_start, color='red', linestyle='--',
                linewidth=1.5, alpha=0.7, label='Intervention')

    ax1.set_ylabel('Response', fontsize=11, fontweight='bold')
    ax1.set_title('Original vs Counterfactual', fontsize=12, fontweight='bold')
    ax1.set_ylim(ylim_panel1)  # ⭐ LÍMITES AJUSTADOS
    ax1.legend(loc='upper left', fontsize=9)
    ax1.grid(True, alpha=0.3)

    # =========================================================================
    # PANEL 2: Point Effects (Efectos Puntuales)
    # =========================================================================
    ax2 = axes[1]

    # Línea verde: Efectos puntuales
    ax2.plot(inferences.index, inferences['point_effects'], 'g-',
             linewidth=2, label='Point Effects')

    # Banda verde: IC del efecto (clipear a límites razonables)
    effects_lower_clipped = inferences['point_effects_lower'].clip(ylim_panel2[0], ylim_panel2[1])
    effects_upper_clipped = inferences['point_effects_upper'].clip(ylim_panel2[0], ylim_panel2[1])

    ax2.fill_between(inferences.index,
                     effects_lower_clipped,
                     effects_upper_clipped,
                     alpha=0.2, color='green', label='95% CI')

    # Línea horizontal en 0
    ax2.axhline(0, color='black', linestyle='-', linewidth=0.8, alpha=0.5)

    # Línea vertical roja
    ax2.axvline(post_period_start, color='red', linestyle='--',
                linewidth=1.5, alpha=0.7)

    ax2.set_ylabel('Point Effect', fontsize=11, fontweight='bold')
    ax2.set_title('Pointwise Effects', fontsize=12, fontweight='bold')
    ax2.set_ylim(ylim_panel2)  # ⭐ LÍMITES AJUSTADOS
    ax2.legend(loc='upper left', fontsize=9)
    ax2.grid(True, alpha=0.3)

    # =========================================================================
    # PANEL 3: Cumulative Effects (Efectos Acumulativos)
    # =========================================================================
    ax3 = axes[2]

    # Crear serie acumulativa desde el inicio de la intervención
    cumulative_effect = inferences['point_effects'].copy()

    # Poner en 0 todo lo anterior al período post
    mask_pre = inferences.index < post_period_start
    cumulative_effect[mask_pre] = 0

    # Calcular acumulativo solo desde el inicio del período post
    mask_post = inferences.index >= post_period_start
    cumulative_effect[mask_post] = inferences.loc[mask_post, 'point_effects'].cumsum()

    # Calcular límites razonables para este panel
    cum_min = cumulative_effect.min()
    cum_max = cumulative_effect.max()
    margin_cum = max(abs(cum_min), abs(cum_max)) * 0.2
    ylim_panel3 = [cum_min - margin_cum, cum_max + margin_cum]

    # Línea morada: Efecto acumulativo
    ax3.plot(inferences.index, cumulative_effect, color='purple',
             linewidth=2, label='Cumulative Effect')

    # Banda morada: IC acumulativo (clipear a límites razonables)
    cum_lower = inferences['point_effects_lower'].copy()
    cum_upper = inferences['point_effects_upper'].copy()
    cum_lower[mask_pre] = 0
    cum_upper[mask_pre] = 0
    cum_lower[mask_post] = inferences.loc[mask_post, 'point_effects_lower'].cumsum()
    cum_upper[mask_post] = inferences.loc[mask_post, 'point_effects_upper'].cumsum()

    # Clipear valores extremos
    cum_lower_clipped = cum_lower.clip(ylim_panel3[0], ylim_panel3[1])
    cum_upper_clipped = cum_upper.clip(ylim_panel3[0], ylim_panel3[1])

    ax3.fill_between(inferences.index, cum_lower_clipped, cum_upper_clipped,
                     alpha=0.2, color='purple', label='95% CI')

    # Línea horizontal en 0
    ax3.axhline(0, color='black', linestyle='-', linewidth=0.8, alpha=0.5)

    # Línea vertical roja
    ax3.axvline(post_period_start, color='red', linestyle='--',
                linewidth=1.5, alpha=0.7)

    ax3.set_ylabel('Cumulative Effect', fontsize=11, fontweight='bold')
    ax3.set_xlabel('Date', fontsize=11, fontweight='bold')
    ax3.set_title('Cumulative Effects', fontsize=12, fontweight='bold')
    ax3.set_ylim(ylim_panel3)  # ⭐ LÍMITES AJUSTADOS
    ax3.legend(loc='upper left', fontsize=9)
    ax3.grid(True, alpha=0.3)

    # Título general
    plt.suptitle(titulo, fontsize=15, fontweight='bold', y=0.995)
    plt.tight_layout()
    plt.show()

    print("✅ Gráficos generados correctamente")

# =============================================================================
# CELDA 6: ANALIZAR INTERVENCIÓN DE ABRIL
# =============================================================================

print("\n" + "="*70)
print("ANÁLISIS: INTERVENCIÓN DE ABRIL (1 abril - 1 mayo)")
print("="*70)

pre_abril = [pd.Timestamp('2023-01-01'), pd.Timestamp('2023-03-31')]
post_abril = [pd.Timestamp('2023-04-01'), pd.Timestamp('2023-05-01')]

print(f"\n📋 Configuración:")
print(f"  • Período PRE:  {pre_abril[0].date()} a {pre_abril[1].date()}")
print(f"  • Período POST: {post_abril[0].date()} a {post_abril[1].date()}")

print(f"\n⚙️ Ejecutando CausalImpact...")

try:
    ci_abril = CausalImpact(
        data,
        pre_abril,
        post_abril,
        model_args={'nseasons': [{'period': 7}], 'standardize': True}
    )
    print("✅ Análisis completado exitosamente")
except Exception as e:
    print(f"❌ Error con todas las variables: {e}")
    data_simple = data[['y', 'sesiones_totales', 'usuarios_unicos']].copy()
    ci_abril = CausalImpact(
        data_simple,
        pre_abril,
        post_abril,
        model_args={'nseasons': [{'period': 7}]}
    )
    print("✅ Análisis completado con variables reducidas")

print("\n" + "─"*70)
print("RESULTADOS ABRIL")
print("─"*70)
print(ci_abril.summary())
print("\n" + ci_abril.summary(output='report'))

print("\n📊 Generando gráficos personalizados...")
plot_causalimpact_correcto(ci_abril, post_abril[0],
                          titulo='Análisis CausalImpact - Intervención Abril 2023')

# Interpretación
print("\n" + "="*70)
print("INTERPRETACIÓN ABRIL")
print("="*70)

summary = ci_abril.summary_data
efecto_promedio = summary['average']['actual'] - summary['average']['predicted']
efecto_total = summary['cumulative']['actual'] - summary['cumulative']['predicted']
efecto_relativo = (efecto_promedio / summary['average']['predicted']) * 100
p_value = ci_abril.p_value

print(f"\n📊 Métricas clave:")
print(f"  • Conversiones promedio observadas: {summary['average']['actual']:.2f}")
print(f"  • Conversiones promedio predichas: {summary['average']['predicted']:.2f}")
print(f"  • Efecto diario promedio: {efecto_promedio:+.2f} conversiones")
print(f"  • Efecto acumulativo total: {efecto_total:+.2f} conversiones")
print(f"  • Cambio porcentual: {efecto_relativo:+.2f}%")
print(f"  • P-valor: {p_value:.4f}")

print(f"\n💡 Conclusión:")
if p_value < 0.01:
    sig = "muy significativo (p < 0.01) ✅✅✅"
elif p_value < 0.05:
    sig = "significativo (p < 0.05) ✅"
elif p_value < 0.10:
    sig = "marginalmente significativo (p < 0.10) ⚠️"
else:
    sig = "NO significativo (p >= 0.10) ❌"

print(f"  El efecto es {sig}")

if p_value < 0.05:
    if efecto_promedio > 0:
        print(f"\n  🎯 La intervención de ABRIL tuvo un impacto POSITIVO:")
        print(f"     • Generó {abs(efecto_promedio):.0f} conversiones adicionales por día")
        print(f"     • Total de {abs(efecto_total):.0f} conversiones extra en el período")
        print(f"     • Aumento del {abs(efecto_relativo):.1f}%")
    else:
        print(f"\n  ⚠️ La intervención de ABRIL tuvo un impacto NEGATIVO:")
        print(f"     • Se perdieron {abs(efecto_promedio):.0f} conversiones por día")
        print(f"     • Total de {abs(efecto_total):.0f} conversiones perdidas")
        print(f"     • Disminución del {abs(efecto_relativo):.1f}%")

# =============================================================================
# CELDA 7: ANALIZAR INTERVENCIÓN DE SEPTIEMBRE
# =============================================================================

print("\n" + "="*70)
print("ANÁLISIS: INTERVENCIÓN DE SEPTIEMBRE (1 sept - 1 oct)")
print("="*70)

pre_sept = [pd.Timestamp('2023-01-01'), pd.Timestamp('2023-08-31')]
post_sept = [pd.Timestamp('2023-09-01'), pd.Timestamp('2023-10-01')]

print(f"\n📋 Configuración:")
print(f"  • Período PRE:  {pre_sept[0].date()} a {pre_sept[1].date()}")
print(f"  • Período POST: {post_sept[0].date()} a {post_sept[1].date()}")

print(f"\n⚙️ Ejecutando CausalImpact...")

try:
    ci_sept = CausalImpact(
        data,
        pre_sept,
        post_sept,
        model_args={'nseasons': [{'period': 7}], 'standardize': True}
    )
    print("✅ Análisis completado exitosamente")
except Exception as e:
    print(f"❌ Error: {e}")
    data_simple = data[['y', 'sesiones_totales', 'usuarios_unicos']].copy()
    ci_sept = CausalImpact(
        data_simple,
        pre_sept,
        post_sept,
        model_args={'nseasons': [{'period': 7}]}
    )
    print("✅ Análisis completado con variables reducidas")

print("\n" + "─"*70)
print("RESULTADOS SEPTIEMBRE")
print("─"*70)
print(ci_sept.summary())
print("\n" + ci_sept.summary(output='report'))

print("\n📊 Generando gráficos personalizados...")
plot_causalimpact_correcto(ci_sept, post_sept[0],
                          titulo='Análisis CausalImpact - Intervención Septiembre 2023')

# Interpretación
print("\n" + "="*70)
print("INTERPRETACIÓN SEPTIEMBRE")
print("="*70)

summary_sept = ci_sept.summary_data
efecto_promedio_sept = summary_sept['average']['actual'] - summary_sept['average']['predicted']
efecto_total_sept = summary_sept['cumulative']['actual'] - summary_sept['cumulative']['predicted']
efecto_relativo_sept = (efecto_promedio_sept / summary_sept['average']['predicted']) * 100
p_value_sept = ci_sept.p_value

print(f"\n📊 Métricas clave:")
print(f"  • Conversiones promedio observadas: {summary_sept['average']['actual']:.2f}")
print(f"  • Conversiones promedio predichas: {summary_sept['average']['predicted']:.2f}")
print(f"  • Efecto diario promedio: {efecto_promedio_sept:+.2f} conversiones")
print(f"  • Efecto acumulativo total: {efecto_total_sept:+.2f} conversiones")
print(f"  • Cambio porcentual: {efecto_relativo_sept:+.2f}%")
print(f"  • P-valor: {p_value_sept:.4f}")

print(f"\n💡 Conclusión:")
if p_value_sept < 0.01:
    sig = "muy significativo (p < 0.01) ✅✅✅"
elif p_value_sept < 0.05:
    sig = "significativo (p < 0.05) ✅"
elif p_value_sept < 0.10:
    sig = "marginalmente significativo (p < 0.10) ⚠️"
else:
    sig = "NO significativo (p >= 0.10) ❌"

print(f"  El efecto es {sig}")

if p_value_sept < 0.05:
    if efecto_promedio_sept > 0:
        print(f"\n  🎯 La intervención de SEPTIEMBRE tuvo un impacto POSITIVO:")
        print(f"     • Generó {abs(efecto_promedio_sept):.0f} conversiones adicionales por día")
        print(f"     • Total de {abs(efecto_total_sept):.0f} conversiones extra")
        print(f"     • Aumento del {abs(efecto_relativo_sept):.1f}%")

# =============================================================================
# CELDA 8: COMPARAR AMBAS INTERVENCIONES
# =============================================================================

print("\n" + "="*70)
print("COMPARACIÓN DE INTERVENCIONES")
print("="*70)

comparacion = pd.DataFrame({
    'Intervención': ['Abril', 'Septiembre'],
    'Efecto_Diario': [efecto_promedio, efecto_promedio_sept],
    'Efecto_Total': [efecto_total, efecto_total_sept],
    'Cambio_%': [efecto_relativo, efecto_relativo_sept],
    'P_value': [p_value, p_value_sept],
    'Significativo': [
        '✅ Sí' if p_value < 0.05 else '❌ No',
        '✅ Sí' if p_value_sept < 0.05 else '❌ No'
    ]
})

print("\n📊 TABLA COMPARATIVA:")
print("─"*70)
print(comparacion.to_string(index=False))

print("\n🏆 RANKING DE EFECTIVIDAD:")
if p_value < 0.05 and p_value_sept < 0.05:
    if abs(efecto_relativo) > abs(efecto_relativo_sept):
        print(f"  1º ABRIL: {efecto_relativo:+.1f}% de cambio")
        print(f"  2º SEPTIEMBRE: {efecto_relativo_sept:+.1f}% de cambio")
    else:
        print(f"  1º SEPTIEMBRE: {efecto_relativo_sept:+.1f}% de cambio")
        print(f"  2º ABRIL: {efecto_relativo:+.1f}% de cambio")
elif p_value < 0.05:
    print(f"  Solo ABRIL mostró efecto significativo ({efecto_relativo:+.1f}%)")
elif p_value_sept < 0.05:
    print(f"  Solo SEPTIEMBRE mostró efecto significativo ({efecto_relativo_sept:+.1f}%)")

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

nombres = comparacion['Intervención']
colors = ['#2ecc71' if p < 0.05 else '#95a5a6' for p in comparacion['P_value']]

axes[0].barh(nombres, comparacion['Efecto_Diario'], color=colors, edgecolor='black')
axes[0].set_xlabel('Conversiones/Día', fontsize=12)
axes[0].set_title('Efecto Diario Promedio', fontweight='bold', fontsize=13)
axes[0].axvline(0, color='black', linewidth=1)
axes[0].grid(True, alpha=0.3, axis='x')
for i, v in enumerate(comparacion['Efecto_Diario']):
    axes[0].text(v, i, f' {v:+.1f}', va='center', fontsize=10, fontweight='bold')

axes[1].barh(nombres, comparacion['Efecto_Total'], color=colors, edgecolor='black')
axes[1].set_xlabel('Conversiones Totales', fontsize=12)
axes[1].set_title('Efecto Acumulativo Total', fontweight='bold', fontsize=13)
axes[1].axvline(0, color='black', linewidth=1)
axes[1].grid(True, alpha=0.3, axis='x')
for i, v in enumerate(comparacion['Efecto_Total']):
    axes[1].text(v, i, f' {v:+.0f}', va='center', fontsize=10, fontweight='bold')

axes[2].barh(nombres, comparacion['Cambio_%'], color=colors, edgecolor='black')
axes[2].set_xlabel('Cambio %', fontsize=12)
axes[2].set_title('Efecto Relativo (%)', fontweight='bold', fontsize=13)
axes[2].axvline(0, color='black', linewidth=1)
axes[2].grid(True, alpha=0.3, axis='x')
for i, v in enumerate(comparacion['Cambio_%']):
    axes[2].text(v, i, f' {v:+.1f}%', va='center', fontsize=10, fontweight='bold')

plt.suptitle('Comparación de Intervenciones - Verde=Significativo, Gris=No Significativo',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n" + "="*70)
print("✅ ANÁLISIS COMPLETADO")
print("="*70)

# =============================================================================
# CELDA 9: GUARDAR RESULTADOS
# =============================================================================

comparacion.to_csv('comparacion_intervenciones.csv', index=False)
ci_abril.inferences.to_csv('serie_temporal_abril.csv')
ci_sept.inferences.to_csv('serie_temporal_septiembre.csv')

print("\n✅ Archivos guardados correctamente")

from google.colab import files
files.download('comparacion_intervenciones.csv')
files.download('serie_temporal_abril.csv')
files.download('serie_temporal_septiembre.csv')

print("\n✅ ¡Todo completado!")